// A comprehensive list of music genres to fill the wheel
export const genres = [
  "acoustic chicago blues", "afro-jazz", "ambient house 16-bit", "arabic reggae", "rock",
  "electro-jungle", "hindi southern rock", "portuguese breakbeat", "korean pacific reggae", 
  "surf flamenco", "trap metal", "dream pop", "synthwave", "lo-fi beats", "k-pop",
  "drill", "grime", "afrobeat", "indie folk", "deep house", "dancehall", "boom bap",
  "ambient techno", "new wave", "chamber pop", "disco jazz", "bubblegum pop", "dark ambient",
  "hard rock", "orchestral", "dreamy psychedelic", "future bass", "acid house", "dancepop",
  "dub techno", "funk soul", "gospel", "hyper-pop", "jangle pop", "krautrock", "math rock",
  "nu-disco", "post-punk", "reggaeton", "shoegaze", "tropicalia", "vaporwave", "witch house",
  "yacht rock", "zydeco", "alt-country", "baroque pop", "chillwave", "detroit techno",
  "emo rap", "french house", "glitch hop", "hardcore punk", "indie rock", "j-pop",
  "kawaii future bass", "latin trap", "melodic dubstep", "noise rock", "outlaw country",
  "progressive house", "queercore", "robot rock", "synthpop", "trip hop", "uk garage",
  "viking metal", "witch house", "xwave", "yacht rock", "zydeco funk", "alternative metal",
  "big band jazz", "celtic folk", "digital hardcore", "ethereal wave", "folk punk", 
  "grime trap", "happy hardcore", "industrial metal", "jungle breaks", "korean indie",
  "lo-fi soul", "metal core", "neo-soul", "old school hip hop", "post-rock",
  "quiet storm", "rumba flamenca", "space disco", "tech house", "uk drill",
  "visual kei", "west coast rap", "xoomii", "york revival", "zen step", "art rock",
  "breakcore", "cloud rap", "djent", "electro swing", "future garage", "g-funk",
  "hip house", "indietronica", "jumpstyle", "kuduro", "liquid funk", "midwest emo",
  "nightcore", "outsider house", "power electronics", "quantum pop", "rave breaks",
  "soul jazz", "tech trance", "uplifting trance", "vocaloid", "wonky", "xtratone",
  "y2k pop", "zouk bass", "acid jazz", "breakbeat hardcore", "cinematic soul", "dark wave",
  "electro house", "footwork", "gabber", "hardbass", "intelligent dance", "jazztronica",
  "k-indie", "lowercase", "melodic death metal", "noise pop", "orchestral dubstep",
  "progressive psytrance", "queer pop", "raw house", "smooth jazz", "technoid",
  "uk funky", "vogue", "wonky funk", "xylopop", "yorkshire bassline", "zeuhl"
]; 